-- AlterTable
ALTER TABLE "Document" ADD COLUMN     "allowDownload" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowFirstPage" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowFullscreen" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowLastPage" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowPrevNext" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowPrint" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowSearchText" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowShare" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowZoom" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "backgroundColor" TEXT,
ADD COLUMN     "backgroundImage" TEXT,
ADD COLUMN     "logoImage" TEXT,
ADD COLUMN     "logoLinkUrl" TEXT,
ADD COLUMN     "logoOpacity" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "logoPosition" "LogoPosition" NOT NULL DEFAULT 'top_left',
ADD COLUMN     "logoSize" INTEGER,
ADD COLUMN     "pageDisposition" "PageDisposition" NOT NULL DEFAULT 'adaptive',
ADD COLUMN     "pageEffect" "PageEffect" NOT NULL DEFAULT 'notebook';
